# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

firstderiv_i <- function(parameters, b, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_CRFCSD_firstderiv_i`, parameters, b, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

g0bmat <- function(rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r) {
    .Call(`_CRFCSD_g0bmat`, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r)
}

NormalConstant <- function(rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r) {
    .Call(`_CRFCSD_NormalConstant`, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r)
}

uijq <- function(rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r) {
    .Call(`_CRFCSD_uijq`, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r)
}

Q1 <- function(parameters, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r, g0bvalue, normalconstant, uijqmat, Cauchyindex) {
    .Call(`_CRFCSD_Q1`, parameters, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r, g0bvalue, normalconstant, uijqmat, Cauchyindex)
}

Q2 <- function(parameters, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r, g0bvalue, normalconstant, uijqmat, tunepar, R, Cauchyindex) {
    .Call(`_CRFCSD_Q2`, parameters, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r, g0bvalue, normalconstant, uijqmat, tunepar, R, Cauchyindex)
}

likelihoodfunc_i <- function(b, parameters, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_CRFCSD_likelihoodfunc_i`, b, parameters, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

Loglikelihood <- function(parameters, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim, tunepar, R, Cauchyindex) {
    .Call(`_CRFCSD_Loglikelihood`, parameters, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim, tunepar, R, Cauchyindex)
}

loglikelihoodtest <- function(parameters, b, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_CRFCSD_loglikelihoodtest`, parameters, b, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

logcauchy <- function(parameters) {
    .Call(`_CRFCSD_logcauchy`, parameters)
}

penaltyterm <- function(psi, lambda, R) {
    .Call(`_CRFCSD_penaltyterm`, psi, lambda, R)
}

firstderiv_icure <- function(parameters, b, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_CRFCSD_firstderiv_icure`, parameters, b, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

g0bcure <- function(b, beta, gamma, eta0, theta, betadim, gammadim, Delta, X, Z, psi, blC, r, ni) {
    .Call(`_CRFCSD_g0bcure`, b, beta, gamma, eta0, theta, betadim, gammadim, Delta, X, Z, psi, blC, r, ni)
}

g0bmatcure <- function(rules, beta, gamma, eta0, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r) {
    .Call(`_CRFCSD_g0bmatcure`, rules, beta, gamma, eta0, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r)
}

NormalConstantcure <- function(rules, beta, gamma, eta0, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r) {
    .Call(`_CRFCSD_NormalConstantcure`, rules, beta, gamma, eta0, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r)
}

uicure <- function(b, beta, gamma, eta0, theta, betadim, gammadim, Delta, X, Z, psi, blC, r, ni) {
    .Call(`_CRFCSD_uicure`, b, beta, gamma, eta0, theta, betadim, gammadim, Delta, X, Z, psi, blC, r, ni)
}

uijqcure <- function(rules, beta, gamma, eta0, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r) {
    .Call(`_CRFCSD_uijqcure`, rules, beta, gamma, eta0, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r)
}

Q1cure <- function(parameters, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r, g0bvalue, normalconstant, uijqmat, Cauchyindex) {
    .Call(`_CRFCSD_Q1cure`, parameters, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r, g0bvalue, normalconstant, uijqmat, Cauchyindex)
}

Q2cure <- function(parameters, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r, g0bvalue, normalconstant, uijqmat, tunepar, R, Cauchyindex) {
    .Call(`_CRFCSD_Q2cure`, parameters, rules, beta, gamma, eta, theta, Delta, betadim, gammadim, n, ni, X, Z, psi, blC, r, g0bvalue, normalconstant, uijqmat, tunepar, R, Cauchyindex)
}

likelihoodfunccure <- function(b, parameters, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_CRFCSD_likelihoodfunccure`, b, parameters, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

Loglikelihoodcure <- function(parameters, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim, tunepar, R, Cauchyindex) {
    .Call(`_CRFCSD_Loglikelihoodcure`, parameters, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim, tunepar, R, Cauchyindex)
}

loglikelihoodtestcure <- function(parameters, b, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_CRFCSD_loglikelihoodtestcure`, parameters, b, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

